// Action constants go here
// Updates the Redux state
const FETCHING_LINE_STATUS = "FETCHING_LINE_STATUS";
const FETCH_LINE_STATUS_SUCCESS = "FETCH_LINE_STATUS_SUCCESS";
const FETCH_LINE_STATUS_FAILURE = "FETCH_LINE_STATUS_FAILURE";

const FETCHING_TWITTER_DATA = "FETCHING_TWITTER_DATA";
const FETCH_TWITTER_DATA_SUCCESS = "FETCH_TWITTER_DATA_SUCCESS";
const FETCH_TWITTER_DATA_FAILURE = "FETCH_TWITTER_DATA_FAILURE";

const CHANGE_SUBSCRIPTION_LINE = "CHANGE_SUBSCRIPTION_LINE";
const SAVING_SUBSCRIPTION_LINE = "SAVING_SUBSCRIPTION_LINE";
const SAVED_SUBSCRIPTION_LINE = "SAVED_SUBSCRIPTION_LINE";
const FAILED_TO_SAVE_SUBSCRIPTION_LINE = "FAILED_TO_SAVE_SUBSCRIPTION_LINE";

const RESTORING_SUBSCRIPTIONS = "RESTORING_SUBSCRIPTIONS";
const RESTORED_SUBSCRIPTIONS = "RESTORED_SUBSCRIPTIONS";
const FAILED_TO_RESTORE_SUBSCRIPTIONS = "FAILED_TO_RESTORE_SUBSCRIPTIONS";

const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export {
  FETCHING_LINE_STATUS,
  FETCH_LINE_STATUS_SUCCESS,
  FETCH_LINE_STATUS_FAILURE,

  FETCHING_TWITTER_DATA,
  FETCH_TWITTER_DATA_SUCCESS,
  FETCH_TWITTER_DATA_FAILURE,

  FETCH_QUESTIONS,
  CHANGE_SUBSCRIPTION_LINE,
  SAVING_SUBSCRIPTION_LINE,
  SAVED_SUBSCRIPTION_LINE,
  FAILED_TO_SAVE_SUBSCRIPTION_LINE,

  RESTORING_SUBSCRIPTIONS,
  RESTORED_SUBSCRIPTIONS,
  FAILED_TO_RESTORE_SUBSCRIPTIONS,
};
