// Action constants go here
// Updates the Redux state
const FETCH_LINE_STATUS = "FETCH_LINE_STATUS";
const FETCH_LINE_STATUS_SUCCESS = "FETCH_LINE_STATUS_SUCCESS";
const FETCH_LINE_STATUS_FAILURE = "FETCH_LINE_STATUS_FAILURE";
export {
  FETCH_LINE_STATUS,
  FETCH_LINE_STATUS_SUCCESS,
  FETCH_LINE_STATUS_FAILURE,
};
