// Action constants go here
// Updates the Redux state
const FETCHING_LINE_STATUS = "FETCHING_LINE_STATUS";
const FETCH_LINE_STATUS_SUCCESS = "FETCH_LINE_STATUS_SUCCESS";
const FETCH_LINE_STATUS_FAILURE = "FETCH_LINE_STATUS_FAILURE";

const FETCHING_TWITTER_DATA = "FETCHING_TWITTER_DATA";
const FETCH_TWITTER_DATA_SUCCESS = "FETCH_TWITTER_DATA_SUCCESS";
const FETCH_TWITTER_DATA_FAILURE = "FETCH_TWITTER_DATA_FAILURE";

const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export {
  FETCHING_LINE_STATUS,
  FETCH_LINE_STATUS_SUCCESS,
  FETCH_LINE_STATUS_FAILURE,

  FETCHING_TWITTER_DATA,
  FETCH_TWITTER_DATA_SUCCESS,
  FETCH_TWITTER_DATA_FAILURE,

  FETCH_QUESTIONS,
};
