# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mrtdown' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mrtdown
  pod 'Firebase/Core'
	pod 'Firebase/Messaging'

  target 'mrtdownTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mrtdown-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mrtdown-tvOS

  target 'mrtdown-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
